trigger:
  - main

pool:
  name: LocalAgent

steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar-scanner.zip"
      Expand-Archive -Path "sonar-scanner.zip" -DestinationPath "."
      $env:PATH += ";$(pwd)\sonar-scanner-5.0.1.3006-windows\bin"
      sonar-scanner `
        -Dsonar.projectKey=gabrgonz21_juice-shop `
        -Dsonar.organization=gabrgonz21 `
        -Dsonar.sources=. `
        -Dsonar.host.url=https://sonarcloud.io `
        -Dsonar.token=$(SONAR_TOKEN)
    displayName: 'Run SonarCloud Scan'